version: '3.7'
services:
  karhub-beer-postgresql:
    image: postgres:16.4
    container_name: karhub-beer-postgresql
    environment:
      POSTGRES_DB: karhub_beer
      POSTGRES_USER: karhub
      POSTGRES_PASSWORD: karhubbeer
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    networks:
      - karhub-beer-network

  karhub-beer-flyway:
    image: flyway/flyway:7.0.2
    container_name: karhub-beer-flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./migrate/changelogs:/flyway/sql
      - ./migrate/flyway.config:/flyway/conf/flyway.config
    networks:
      - karhub-beer-network

  karhub-beer-redis:
    image: redis:7.4
    container_name: karhub-beer-redis
    ports:
      - "6379:6379"
    networks:
      - karhub-beer-network

  karhub-keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: karhub-keycloak
    command: start-dev
    environment:
      TZ: America/Belem
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://karhub-beer-postgresql:5432/keycloak
      KC_DB_USERNAME: karhub
      KC_DB_PASSWORD: karhubbeer
      KC_HOSTNAME_URL: http://localhost:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - karhub-beer-postgresql
    networks:
      - karhub-beer-network

networks:
  karhub-beer-network:
    driver: bridge
    name: karhub-beer-network
